apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: {{ .Values.letsencrypt_email }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: {{ .Values.letsencrypt_email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ssl-com
spec:
  acme:
    email: {{ .Values.letsencrypt_email }}
    server: https://acme.ssl.com/sslcom-dv-rsa
    externalAccountBinding:
      keyID: {{ .Values.sslcom_keyid }}
      keySecretRef:
        name: sslcom-hmac-key 
        key: secret
      keyAlgorithm: HS256
    privateKeySecretRef:
        name: sslcom-private-hmac-key 
    solvers:
    - http01:
        ingress:
          class: nginx
